language: go

go:
  - 1.16.3

os:
  - linux
  - osx
  - windows

before_install:
  - go mod tidy

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

